Repository WildCodeSchool-2023-09/JS-RMT-React_If-Projet3-Wildy-Gamy, pull requests merged in 2024-01, with the labels that each got.

#3 jeu tictactoe
  frontend/components/TicTacToeComponents/Board.jsx
  frontend/components/TicTacToeComponents/Square.jsx
  frontend/src/assets/fond7.jpg
  frontend/src/assets/tictactoe.JPG
  frontend/src/pages/Home.jsx
  frontend/src/pages/TicTacToe.jsx
  frontend/src/style/components/TicTacToe.scss
  frontend/src/style/index.scss
Labels: review formateur

#5 deplacement de tictactoe component dans src
  frontend/src/components/TicTacToeComponents/Board.jsx
  frontend/src/components/TicTacToeComponents/Square.jsx
  frontend/src/pages/TicTacToe.jsx
Labels: review formateur

#4 Users admin page
  backend/src/controllers/playerControllers.js
  backend/src/models/PlayerManager.js
  backend/src/router.js
  backend/src/tables.js
  frontend/src/components/AdminUsersTable.jsx
  frontend/src/components/DeleteButton.jsx
  frontend/src/components/InputSearchBar.jsx
  frontend/src/main.jsx
  frontend/src/pages/AdminUsersPage.jsx
  frontend/src/style/components/AdminUsersTable.scss
  frontend/src/style/components/DeleteButton.scss
  frontend/src/style/components/InputSearchBar.scss
  frontend/src/style/pages/AdminUsersPage.scss
Labels: review formateur

#6 Seed and admin theo
  backend/database/schema.sql
  backend/seed.js
  backend/src/controllers/partyControllers.js
  backend/src/models/ItemManager.js
  backend/src/models/PartyManager.js
  backend/src/router.js
  backend/src/services/time.js
  backend/src/tables.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/AdminUsersTable.jsx
  frontend/src/components/charts/BarChart.jsx
  frontend/src/components/charts/CamenbertChart.jsx
  frontend/src/pages/AdminGame.jsx
  frontend/src/services/connexion.js
  frontend/src/style/components/camenbertGame.scss
  frontend/src/style/index.scss
  frontend/src/style/pages/AdminPartyPage.scss
  frontend/src/style/settings.scss
Labels: review formateur

#8 Contacts
  backend/package-lock.json
  backend/package.json
  backend/src/controllers/contactControllers.js
  backend/src/controllers/partyControllers.js
  backend/src/router.js
  backend/src/services/mail.js
  frontend/src/components/Contact/Contact.jsx
  frontend/src/components/Contact/InputContact.jsx
  frontend/src/main.jsx
  frontend/src/pages/Home.jsx
  frontend/src/style/components/contact.scss
  frontend/src/style/index.scss
Labels: review formateur

#9 Carousel/jeux
  backend/public/assets/images/favicon.png
  backend/src/controllers/gameControllers.js
  backend/src/models/GameManager.js
  backend/src/router.js
  backend/src/tables.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/next-button.png
  frontend/src/assets/previous-button.png
  frontend/src/assets/tictactoe.png
  frontend/src/components/AdminUsersTable.jsx
  frontend/src/components/DeleteButton.jsx
  frontend/src/components/InputSearchBar.jsx
  frontend/src/components/carousel/Carousel.jsx
  frontend/src/main.jsx
  frontend/src/pages/AdminUsersPage.jsx
  frontend/src/pages/Home.jsx
  frontend/src/style/components/Carousel.scss
  frontend/src/style/index.scss
Labels: review formateur

#10 Leader board
  backend/seed.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/assets/icons8-home.svg
  frontend/src/assets/icons8-stats-32.png
  frontend/src/assets/icons8-user-32.png
  frontend/src/assets/icons8-user-70.png
  frontend/src/assets/icons8-user-96.png
  frontend/src/components/LeaderBoard/LeaderBoard.jsx
  frontend/src/components/LeaderBoard/LeaderBoardLine.jsx
  frontend/src/components/LeaderBoard/LeaderBoardMobile.jsx
  frontend/src/components/nav/navAdmin.jsx
  frontend/src/pages/AdminPage.jsx
  frontend/src/pages/Home.jsx
  frontend/src/style/components/AdminUsersTable.scss
  frontend/src/style/components/LeaderBoard/LeaderBoard.scss
  frontend/src/style/components/camenbertGame.scss
  frontend/src/style/components/nav.scss
  frontend/src/style/index.scss
  frontend/src/style/pages/AdminUsersPage.scss
  frontend/src/style/settings.scss
Labels: review formateur

#12 hotfixe du css form et carouselle
  frontend/src/App.jsx
  frontend/src/components/carousel/Carousel.jsx
  frontend/src/style/components/Carousel.scss
  frontend/src/style/components/LeaderBoard/LeaderBoard.scss
  frontend/src/style/components/contact.scss
  frontend/src/style/settings.scss
Labels: review formateur

#13 Inscription
  frontend/src/assets/imageLogin2.png
  frontend/src/components/input/InputComponents.jsx
  frontend/src/main.jsx
  frontend/src/pages/auth/Signup.jsx
  frontend/src/style/components/InputComponents.scss
  frontend/src/style/index.scss
  frontend/src/style/pages/Signup.scss
Labels: Change Asked

#16 Login
  backend/seed.js
  backend/src/controllers/playerControllers.js
  backend/src/models/PlayerManager.js
  backend/src/router.js
  backend/src/tables.js
  frontend/src/main.jsx
Labels: review formateur, MH en relecture

#14 Home game
  backend/src/controllers/gameControllers.js
  backend/src/models/GameManager.js
  backend/src/router.js
  frontend/src/assets/tictactoe.JPG
  frontend/src/components/ListGames.jsx
  frontend/src/components/carousel/Carousel.jsx
  frontend/src/main.jsx
  frontend/src/pages/Home.jsx
  frontend/src/pages/InfoGame.jsx
  frontend/src/style/components/Carousel.scss
  frontend/src/style/components/LeaderBoard/LeaderBoard.scss
  frontend/src/style/components/ListGames.scss
  frontend/src/style/index.scss
  frontend/src/style/pages/Home.scss
  frontend/src/style/pages/InfoGame.scss
  frontend/src/style/settings.scss
Labels: review team

#21 fix css des components de la page home et de la page home
  frontend/src/pages/Home.jsx
  frontend/src/style/components/Carousel.scss
  frontend/src/style/components/LeaderBoard/LeaderBoard.scss
  frontend/src/style/components/ListGames.scss
  frontend/src/style/components/contact.scss
  frontend/src/style/pages/Home.scss
Labels: review formateur, MH en relecture

#20 ajout du context + contextLogin + formulaire
  backend/package-lock.json
  backend/package.json
  backend/src/controllers/playerControllers.js
  backend/src/controllers/profilControllers.js
  backend/src/models/ProfilManager.js
  backend/src/router.js
  backend/src/services/jwt.js
  backend/src/tables.js
  frontend/context/AuthContext.jsx
  frontend/src/main.jsx
  frontend/src/pages/auth/Login.jsx
Labels: Change Asked

#22 style sur la page login
  frontend/src/pages/auth/Login.jsx
  frontend/src/style/index.scss
  frontend/src/style/pages/Login.scss
Labels: review formateur
