Repository WildCodeSchool-2023-09/JS-RMT-React_If-Projet3-Wildy-Gamy, pull requests merged in 2024-02, with the labels that each got.

#24 Profil container
  backend/database/schema.sql
  backend/src/controllers/partyControllers.js
  backend/src/controllers/playerControllers.js
  backend/src/models/PartyManager.js
  backend/src/router.js
  frontend/context/AuthContext.jsx
  frontend/src/components/profilContainer/Profile.jsx
  frontend/src/pages/Home.jsx
  frontend/src/pages/auth/Login.jsx
  frontend/src/services/convertTime.js
  frontend/src/services/divisions.js
  frontend/src/style/index.scss
  frontend/src/style/pages/Profil.scss
Labels: review team

#25 Pagination/login signup
  backend/package-lock.json
  backend/package.json
  backend/src/app.js
  backend/src/controllers/playerControllers.js
  backend/src/router.js
  frontend/context/AuthContext.jsx
  frontend/src/assets/logo.png
  frontend/src/components/header/Header.jsx
  frontend/src/components/input/ButtonConected.jsx
  frontend/src/pages/Home.jsx
  frontend/src/pages/auth/Login.jsx
  frontend/src/style/components/ButtonConnected.scss
  frontend/src/style/components/Header.scss
  frontend/src/style/index.scss
  frontend/src/style/pages/Login.scss
Labels: Change Asked, review team, MH en relecture

#23 Comment
  backend/database/schema.sql
  backend/package-lock.json
  backend/package.json
  backend/src/controllers/commentControllers.js
  backend/src/models/CommentManager.js
  backend/src/router.js
  backend/src/tables.js
  backend/src/validators/validateComment.js
  frontend/src/components/Comment.jsx
  frontend/src/main.jsx
  frontend/src/pages/Home.jsx
  frontend/src/pages/PageComment.jsx
  frontend/src/style/components/Comment.scss
  frontend/src/style/index.scss
  frontend/src/style/pages/PageComment.scss
Labels: review formateur

#26 fix css profil et formulaire
  frontend/src/components/profilContainer/Profile.jsx
  frontend/src/pages/Home.jsx
  frontend/src/style/components/contact.scss
  frontend/src/style/pages/Home.scss
  frontend/src/style/pages/Profil.scss
Labels: review formateur

#28 Page profil
  frontend/src/assets/trophy.svg
  frontend/src/components/ProfilPage/InfoProfil.jsx
  frontend/src/components/ProfilPage/ProfilBio.jsx
  frontend/src/components/ProfilPage/Rancking.jsx
  frontend/src/components/header/Header.jsx
  frontend/src/components/input/InputProfil.jsx
  frontend/src/main.jsx
  frontend/src/pages/ProfilPage.jsx
  frontend/src/services/cupColors.js
Labels: review formateur

#29 redirection du login vers signup avec un link + css
  frontend/src/pages/auth/Login.jsx
  frontend/src/style/pages/Login.scss
Labels: review formateur

#30 modif css comment
  frontend/src/components/Comment.jsx
  frontend/src/style/components/Comment.scss
  frontend/src/style/pages/PageComment.scss
Labels: review formateur

#31 fix css du caroussel
  frontend/src/style/components/Carousel.scss
Labels: review formateur

#32 Profil
  backend/src/controllers/playerControllers.js
  backend/src/models/PartyManager.js
  frontend/context/AuthContext.jsx
  frontend/src/assets/trophy/trophy(1).svg
  frontend/src/assets/trophy/trophy(2).svg
  frontend/src/assets/trophy/trophy(3).svg
  frontend/src/assets/trophy/trophy(4).svg
  frontend/src/assets/trophy/trophy(5).svg
  frontend/src/components/ProfilPage/Rancking.jsx
  frontend/src/components/profilContainer/Profile.jsx
  frontend/src/pages/ProfilPage.jsx
  frontend/src/services/cupColors.js
Labels: review formateur

#33 fix des images
  backend/seed.js
Labels: review formateur

#34 modif css info
  frontend/src/assets/logo2.png
  frontend/src/components/carousel/Carousel.jsx
  frontend/src/main.jsx
  frontend/src/pages/InfoGame.jsx
  frontend/src/pages/PageComment.jsx
  frontend/src/pages/TicTacToe.jsx
  frontend/src/style/components/TicTacToe.scss
  frontend/src/style/pages/InfoGame.scss
  frontend/src/style/pages/PageComment.scss
Labels: review formateur

#35 ajout du link vers admin
  frontend/src/components/carousel/Carousel.jsx
  frontend/src/components/header/Header.jsx
  frontend/src/components/input/AdminButton.jsx
  frontend/src/components/nav/navAdmin.jsx
Labels: review formateur

#36 modif css page info et home
  frontend/src/components/header/Header.jsx
  frontend/src/style/components/Header.scss
  frontend/src/style/pages/Home.scss
  frontend/src/style/pages/InfoGame.scss
Labels: review formateur

#40 fix css admin
  frontend/src/components/AdminUsersTable.jsx
  frontend/src/style/components/AdminUsersTable.scss
Labels: review formateur

#42 Hotfixe css wg
  frontend/index.html
  frontend/src/assets/icons8-admin-55.png
  frontend/src/assets/icons8-admin-57.png
  frontend/src/assets/icons8-user-70.png
  frontend/src/components/header/Header.jsx
  frontend/src/components/input/AdminButton.jsx
  frontend/src/components/input/InputProfil.jsx
  frontend/src/style/components/Header.scss
  frontend/src/style/components/LeaderBoard/LeaderBoard.scss
Labels: review formateur

#43 fix css navbar
  frontend/src/components/header/Header.jsx
  frontend/src/style/components/ButtonConnected.scss
  frontend/src/style/components/Header.scss
Labels: review formateur

#45 dernier commit promis
  backend/seed.js
  frontend/src/components/Contact/tictactoe.png
  frontend/src/components/header/Header.jsx
  frontend/src/components/profilContainer/Profile.jsx
Labels: review formateur
